export const mockInvoices = [
  {
    id: 1,
    clientName: 'John Doe',
    clientEmail: 'john@example.com',
    description: 'Web Development Services',
    amount: 1500,
    status: 'paid',
    dueDate: '2024-05-01',
    createdAt: '2024-04-01',
  },
  {
    id: 2,
    clientName: 'Jane Smith',
    clientEmail: 'jane@example.com',
    description: 'Design Consultation',
    amount: 800,
    status: 'pending',
    dueDate: '2024-05-15',
    createdAt: '2024-04-10',
  },
  {
    id: 3,
    clientName: 'Bob Johnson',
    clientEmail: 'bob@example.com',
    description: 'SEO Optimization',
    amount: 1200,
    status: 'draft',
    dueDate: '2024-06-01',
    createdAt: '2024-04-20',
  },
];